[package]
name = "zetalan"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
crossterm = "0.29.0"
rand = "0.9.2"
rand_chacha = "0.9.0"
ratatui = "0.29.0"
socket2 = "0.6.1"
tokio = { version = "1.48.0", features = ["full"] }
tui-big-text = "0.7.3"
